POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmdVc2VyIiwiaWQiOiI2MmJiZTEwYzFkYzlmYzBlMDVkZTVhZWYiLCJpYXQiOjE2NTY0ODM4NTB9.FaigKsTLa-zClyCbgRPYakAKzPnFpU7gl2F5cnNUS3E

{
  "content": "another note from vscode with user token in header",
  "important": true
}